### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by hasangokce** [hasangokce/roggl#41]
## Functional requirements

- [ ] remove page
- [ ] login/logout
- [ ] slider of paragraphs component

## Deployment package
- [ ] design documents
- [ ] implementation_files
- [ ] demonstration of its functionality
- [ ] conclusions including future work
- [ ] Name your file as: SWE599-Project-2020S-Gokce-Hasan.doc (or docx or pdf)
- [ ] Turnitin report

## Enroll to Turnitin with
- Class Id: 2495514
- Enrollment Key: 2020@swe

## Presentation
- [ ] You are expected to DEMO your project while presenting it to your project advisor.
